mod default_move_system;
pub use default_move_system::DefaultMoveAI;
mod cow_ai_system;
pub use cow_ai_system::CowAI;
mod carnivorous_ai_system;
pub use carnivorous_ai_system::CarnivorousAI;
mod flee_ai_system;
pub use flee_ai_system::FleeAI;
mod omnivore_ai_system;
pub use omnivore_ai_system::OmnivoreAI;
mod seach_parter_ai;
pub use seach_parter_ai::SearchParterAI;
mod targeting_ai;
pub use targeting_ai::TargetingAI;
mod eating_ai;
pub use eating_ai::EatingKillingAI;
mod approach_ai_system;
pub use approach_ai_system::ApproachAI;

mod monster_ai_system;
pub use monster_ai_system::MonsterAI;
